target: _site

url: https://www.isaacteh.me
baseurl: /

categories:
  - home
  - about
  - resume
  - portfolio
  - contact

data:
  - _data

pageviews:
  - _pages

theme: bootstrap

title: Isaac Teh Site

templates:
  redirect: false

debug: false

scss:
  style: compressed
  sourcemap: false
